---
title: "COVID-19 in Virginia"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    social: menu
    source_code: https://github.com/joseph-ellis/va-covid
    theme: paper
runtime: shiny
---

<!-- TODO - Move any style written here to its own CSS file -->
<style>
  .panel {
    margin-top: 10px;
  }
  
  .panel-title {
    font-size: 18px;
  }
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE, 
  message = FALSE, 
  warning = FALSE
)
 # load necessary packages
library(config)
library(flexdashboard)
library(lubridate)
library(RSocrata)
library(scales)
library(shiny)
library(shinyEffects)
library(shinyjs)
library(shinythemes)
library(shinyWidgets)
library(tidyverse)
library(highcharter)

# load globals
source("R/global.R")

# load necessary components
source("components/highChartSingleLineDate.R")
source("components/highChartColumnLineDate.R")

# load all data
covid <- readRDS("data/covid.rds")

```


State Metric Summary {data-navmenu="State"}
===============================================================================

Sidebar {.sidebar}
-------------------------------------------------------------------------------
```{r global-sidebar}

# metrics showing counted values
metricsCount <- c(
  "Total Cases",
  "Total Hospitalizations",
  "Total Deaths"
)

# metrics showing rates
metricsRate <- c(
  "Cases per 100K",
  "Hospitalization Rate",
  "Hospitalization per 100K",
  "Mortality Rate",
  "Deaths per 100K"
)

# metrics showing daily new values
metricsNew <- c(
  "New Cases",
  "New Hospitalizations",
  "New Deaths"
)

# user input panel
panel(
  heading = "User Inputs",
  status = "primary",
  prettyRadioButtons(
    inputId = "stateChartType",
    label = "What to plot...", 
    choices = c(
      "Cumulative Totals",
      "Daily New Values"
    ),
    icon = icon("check"), 
    bigger = TRUE,
    status = "primary"
  ),
  pickerInput(
    inputId = "metric",
    label = "Choose a metric...", 
    choices = list(
      Counts = metricsCount,
      Rates = metricsRate
    ),
    selected = "Total Cases"
  )
)

# change metrics in the dropdown menu based on selected chart type
observeEvent(input$stateChartType, {
  metricChoices <- switch(
    input$stateChartType,
    "Cumulative Totals" = list(
      Counts = metricsCount,
      Rates = metricsRate
    ),
    "Daily New Values" = metricsNew
  )
  
  updatePickerInput(
    session = session,
    inputId = "metric",
    choices = metricChoices
  )
})

```

Row
-------------------------------------------------------------------------------
### Total Cases
```{r value-box_total-cases}

# display total cases
valueBox(
  value = format(covid$SCMS$TotalCases, big.mark = ","),
  icon = "fa-thermometer-three-quarters",
  color = "danger"
)

```

### Hospitalizations
```{r value-box_hospitalizations}

# display total hospitalizations
valueBox(
  value = format(covid$SCMS$Hospitalizations, big.mark = ","),
  icon = "fa-hospital",
  color = "danger"
)

```

### Deaths
```{r value-box_deaths}

# display total deaths
valueBox(
  value = format(covid$SCMS$Deaths, big.mark = ","),
  icon = "fa-ambulance",
  color = "danger"
)

```

Row
-------------------------------------------------------------------------------
### Cases per 100K
```{r value-box_cases-100k}

# display cases per 100K 
valueBox(
  value = format(
    round(covid$SCMS$CasesPer100K),
    big.mark = ","
  ),
  icon = "fa-users",
  color = "warning"
)

```

### Hospitalizations Rate
```{r value-box_hospital_rate}

# display hospitalization rate
valueBox(
  value = percent(covid$SCMS$PercentCasesHospitalized, accuracy = 0.1),
  icon = "fa-hospital",
  color = "warning"
)

```

### Mortality Rate
```{r value-box_mortality_rate}

# display mortality rate
valueBox(
  value = percent(covid$SCMS$MortalityRate, accuracy = 0.1),
  icon = "fa-ambulance",
  color = "warning"
)

```

Row
-------------------------------------------------------------------------------

### `r renderUI("<h5>State Summary Metrics</h5>" %>% lapply(htmltools::HTML))`
```{r hc_state}

stateChartData <- eventReactive(input$metric, {
  chosenMetric <- switch(
    input$metric,
    "Total Cases" = "TotalCases",
    "Total Hospitalizations" = "Hospitalizations",
    "Total Deaths" = "Deaths",
    "Cases per 100K" = "CasesPer100K",
    "Hospitalization Rate" = "PercentCasesHospitalized",
    "Hospitalization per 100K" = "HospitalizationsPer100K",
    "Mortality Rate" = "MortalityRate",
    "Deaths per 100K" = "DeathsPer100K",
    "New Cases" = "NewCases",
    "New Hospitalizations" = "NewHospitalizations",
    "New Deaths" = "NewDeaths" 
  )
  
  chosenAverage <- switch(
    input$metric,
    "New Cases" = "NewCases_7MA",
    "New Hospitalizations" = "NewHospitalizations_7MA",
    "New Deaths" = "NewDeaths_7MA" 
  )
  
  output <- switch(
    input$stateChartType,
    "Cumulative Totals" = covid$SMSBD %>% 
      select("plotX" = Date, "plotY" = all_of(chosenMetric)),
    "Daily New Values" = covid$SNMSBD %>% 
      select("plotX" = Date, "plotYC" = all_of(chosenMetric), "plotYL" = all_of(chosenAverage))
  )
})

yAxisTitle <- eventReactive(input$metric, {
  output <- input$metric
})

stateSummaryPlotter <- eventReactive(input$metric, {
  switch(
    input$stateChartType,
    "Cumulative Totals" = HighChartSingleLineDate(stateChartData, yAxisTitle) %>%
      StyleSingleLineDate(yAxisTitle),
    "Daily New Values" = HighChartColumnLineDate(stateChartData, yAxisTitle) %>%
      StyleColumnLineDate(yAxisTitle)
  )
})

renderHighchart({
  stateSummaryPlotter()
})

```

State Metrics by Subgroups {data-navmenu="State"}
===============================================================================

Health District Metrics
===============================================================================


Locality Metrics
===============================================================================
